### ISSUE TITLE
[Design Proposal] Daemonize slave

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/factorioClusterio#201]
I'm thinking it would be better if a slave would work more like a daemon that managed and ran multiple Factorio instances.  The advantage of this being that you could manage the instances better from the master server this way, having for example the option to implement a web panel on the master server that starts and stop individual instances.  Maybe a future feature based on this could be a button/api that moves an instance from one slave to another for ease of load balancing.

**Comment by Danielv123** [comment]
I was working on this ages ago, that was the intention behind serverManager. I never got that far though. Main issues I ran into:

1. Client.js is monolithic and ugly. There is no good way of programatically starting a new slave through it. As we are working towards compartimentalization and a more testable codebase, solving this at the same time would make sense.

2. Thats about it I guess.

**Comment by Godmave** [comment]
This would also take over some/all of the functionality of the bird panel. You would only set up the daemon which connects to the master and allows to spawn and manage instances from there. You could still have the whole thing inside a docker container for easy deployment.

**Comment by psihius** [comment]
I actually have an idea since there have been some developments on the front of a management server thingie that can do all we need. See Discord :)

**Comment by Hornwitser** [comment]
Please don't make vague references to discussions that has happened on Discord in issues.  It's impossible to find the discussion at a later point in time.  Discord lets you [link directly to the relevant message](https://discordapp.com/channels/450361298220351489/450361706426925066/614414110561665075) either use that or don't mention the discussion at all.

**Comment by psihius** [comment]
https://discordapp.com/channels/450361298220351489/450361706426925066/614414110561665075

**Comment by Hornwitser** [comment]
This was implemented in #261.
