### ISSUE TITLE
Create a better way to obtain the first web interface admin account

### ISSUE THREAD

**Issue by Danielv123** [clusterio/factorioClusterio#202]
Currently you have to edit ./database/playerManager.json to create the first web interface admin account. This is stupid.

Suggestions:

* First account becomes admin automatically

* Default to having an admin:admin login

* Use the interactive console to confirm the first account as admin account

* Enter masterAuthToken in web interface to make yourself admin (the APIs for this exist already, just not the UI)

**Comment by Hornwitser** [comment]
I'd like an interactive create user interface on the console that lets your specify the name and password.  Sort of like `useradd` on Linux.  Maybe there could be a setup wizard that had it as a step.

**Comment by Morranr** [comment]
How about if there isn't any admin accounts, when master starts up, it generates a temporary token which it prints to the console with short instruction to use it to create an admin account on the web interface.  On the web interface itself, add an optional field for the token when creating a new account that would make it admin on creation, and somewhere to upgrade a non-admin account with the token (if they already made an account before realizing about the token).

Benefits over other suggestions: more secure than first account/default admin account, and doesn't require an interactive console.  It is fairly similar to using the masterAuthToken, though I'm not sure which would be easier for someone setting it up for the first time to understand.  A separate token would allow it to be either single-use or multi-use though, if that would be desired; masterAuthToken would almost have to be multi-use.

Just another possible idea.  :-)

**Comment by Danielv123** [comment]
masterAuthToken as auth on the web interface APIs is already implemented, so it makes sense to use that. We also have the option of generating auth tokens with different validity times - the default token is valid for 1 year.

jwt.sign({ id: "api" }, config.masterAuthSecret, {
	expiresIn: 86400*365 // expires in 1 year
})

**Comment by Hornwitser** [comment]
Implemented by #299.  An admin account is created with `node master bootstrap create-admin <user>` and a clusterctl config for access through the created admin account can be made with a similar `create-ctl-confg` command.
