### ISSUE TITLE
[Refactoring] Cleanup config.json loading and remove hardcoded instances for file paths.

### ISSUE THREAD

**Issue by psihius** [clusterio/factorioClusterio#207]
Allow specifying the config file via a command-line argument to make it much more flexible.

**Comment by Hornwitser** [comment]
We already allow passing `--config path/to/config` while launching both master.js and client.js.  But this isn't documented and there's still places that's hard coding `config.json`.

**Comment by psihius** [comment]
Well, config.json cleanup should be done here anyway, changed the title

**Comment by Hornwitser** [comment]
config.json has been cleaned up.  That is to say it's gone.  The new config files all allow the path to them to be specified via a command line argument.
