### ISSUE TITLE
[Refactoring] Split master and client configuration files

### ISSUE THREAD

**Issue by psihius** [clusterio/factorioClusterio#208]
Having config options for both in the same file can be somewhat confusing, especially when there are no comments about what part of the Clusterio specific option affects. Related to #200 proposal

**Comment by Hornwitser** [comment]
I kind of want to split the master and slave codebase into two.  Why should the slaves have to install all the dependencies and code of the master server when none of them will be using it?

**Comment by Hornwitser** [comment]
Config files have been separated by #261.
