### ISSUE TITLE
Issues with Factorissimo2

### ISSUE THREAD

**Issue by Fank** [clusterio/factorioClusterio#257]
Factorissimo have items (factory buildings) with the name `factory-1`, `factory-2` and `factory-3` these can be transported from server to server without any issues.
When a factory is placed the item will be renamed to `factory-3-s<floor number>` e.g. `factory-3-s10` or `factory-3-s11`and a floor aka new world inside a server will be created.
It can be easily removed and placed somewhere else.

But now the issue, when this building is transmitted i can see it, but i will not be able to request it again, because it has a different name now with the floor name as suffix. So its gone forever.
![image](https://user-images.githubusercontent.com/1900106/69097242-72572380-0a56-11ea-9995-afce5f492723.png)

I would prefer to blacklist the item, if it was placed, and make it not transferable because it was initialized on the server.

**Comment by Danielv123** [comment]
So what you need is something like the current ingame blacklist, except being able to specify items using pattern matching, ex blacklist factory-?-*
This might be possible to implement in the Lua mod using glob patterns.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by psihius** [comment]
Interesting catch you had there. Thanks for reporting, we shall see what we can do about this.

**Comment by Fank** [comment]
Yea something like a pattern, to filter those should work.

**Comment by chrisgbk** [comment]
Lua patterns work well for this, something like:
```lua
local test_items = {
  'factory-3',
  'factory-3-s10',
  'random-item',
  'some-mod-item',
  'some-mod-item2'
}

local blacklist = {
  {name = '^factory%-%d*%-', pattern = true},
  {name = 'some-mod-item'}
}

local function is_blacklisted(item)
  for _,v in pairs(blacklist) do
    local p = v.pattern
    local i, j = item:find(v.name, 1, not p)
    if i then
      --[[
      find returns a substring, if using plain matching we want
      an exact match only (ie: length of substring == length of string)
      
      the alternative to this is enabling pattern matching always,
      escaping the item name and putting start/end anchors if not a pattern
      ]]
      if p or ((i == 1) and ((j - i + 1) == #item)) then
        return true
      end
    end
  end
  return false
end

for _,item in pairs(test_items) do
  if is_blacklisted(item) then
    print(item .. ' is blacklisted')
  else
    print(item .. ' is not blacklisted')
  end
end
```
```
factory-3 is not blacklisted
factory-3-s10 is blacklisted
random-item is not blacklisted
some-mod-item is blacklisted
some-mod-item2 is not blacklisted

```

**Comment by psihius** [comment]
As I said in #259 , this actually might be a job for a plugin that applies Factorissimo specific fixes to Clusterio.

**Comment by Fank** [comment]
I am not sure about it, maybe yes maybe no. But i think to have something like blacklisting system will always open the ability to prevent transmitting stuff, which can be defined by server owners aswell.
When someone like to prevent transporting e.g. science packs it can be easily done.

**Comment by Fank** [comment]
A blacklisting plugin for transmitting would make sence, which can handle item, fluid and electricty limitations

**Comment by Danielv123** [comment]
If this is still desired, post a feature request in https://github.com/clusterio/factorioClusterioMod
