### ISSUE TITLE
2.0 logger.warning is not a function

### ISSUE THREAD

**Issue by Danielv123** [clusterio/factorioClusterio#303]
When starting an instance while having an unzipped mod in sharedMods it fails with this error in the slave config:

```
Unexpected error while responding to start_instance_request TypeError: logger.warning is not a function
    at symlinkMods (/home/danielv/factorioClusterio/slave.js:1195:11)
```

This should be handled by logging a warn about not using folder mods or by supporting folder mods.

**Comment by Hornwitser** [comment]
That's exactly what I implemented.  Unfortunately I mixed up `console.warn` with python's logging module which uses 
`logger.warning`.
