### ISSUE TITLE
How could I use this mod to just send a signal to an external file/net socket (without cluster, master server and all the networking)?

### ISSUE THREAD

**Issue by adamryczkowski** [clusterio/factorioClusterio#317]
We have a server running non-stop (without pauses) at home. We also like tinkering with Arduino/ESP8266. We would love to have some real-world alerts about our Facorio world with LEDs connected to a microcontroller. So we could propagate events like "the turrets went out of ammo" to the real-world, to keep the game haunting us on every single moment of our lives :-D. 

Maybe the Clustorio server can keep the contents of a small text file to reflect a signal network state, so we can pull the changes ourselves using an external process, Maybe the Clustorio server can push changes of the state of the signal network to a net socket/web socket/whatever.

We never programmed anything in Factorio, but we do write software and we may contribute back if you give us some pointers.

**Comment by Danielv123** [comment]
Clusterio did once support this, but it was extracted into a standalone mod as it was lacking maintainance and justarandomgeek did a version fast enough to run his IP layer: https://github.com/justarandomgeek/FactorioIP/tree/master/RoutableCombinators

If you want to monitor things with clusterio, the standard way of doing it is using a stock clusterio install with Prometheus for gathering timeseries data and either prometheus/grafana for creating alerts. Both have a simple http API you can call from your microcontrollers.

Configuring prometheus to ingest metrics from clusterio is literally 5 lines of config, I grafana has a nice GUI that should be pretty easy to understand.

Making the clusterio mod run without the master and slave sounds like too much work for no benefit. In this case, I suggest lifting the statistics exporting parts out of the mod and dropping it in a scenario script or a minimal mod and writing the external layer yourself.

Overall, this sounds like a cool project.

**Comment by psihius** [comment]
Clusterio is a cluster - so master and stuff is required and we never plan to make it work on its own. So it's either use the whole thing or not.

For simple dump of circuit network state, you can use modding API to make a scenario that reads what you need and dumps it into the text file (that's how we do a lot of our data export in the 1.x version series, we switched to full RCON in 2.0-dev).
For modding factorio you are better off joining the Factorio discord - https://discord.gg/5r9aQpX - and talking to people in #mod-making. Clusterio way is not a simple one ;)

**Comment by adamryczkowski** [comment]
Thank you for the answers! I'll look into the discord channel.
