### ISSUE TITLE
Could you please make a mod to show the basic mechanism of this epic mod.

### ISSUE THREAD

**Issue by YagaoDirac** [clusterio/factorioClusterio#322]
I tried to extract the method of communicating inside and outside Factorio. I know the game.write_file could at least output data. But when I tried to read the input part, the remote.add_interface, commands.add_command("ccri",...), commands.add_command("ccrm",...), I have no idea how these commands are called. Is it from the js part?

Could you please make a mod as a tutorial to show the basic mechanism of Clusterio. I planned to make some one-mod-scenario, and with some kinds of long term design, which needs this mechanism.
Thanks.

**Comment by Hornwitser** [comment]
/ccri and /ccrm are not used and I don't think they ever were used.  The project is in the middle of a major rewrite for 2.0 so things are subject to change.

The js code is responsible for running the Factorio servers and handing the communication between them.  It connects over RCON to send data to Factorio and listens on stdout to receive data from Factorio.  You can see examples of both things in the subspace storage plugin https://github.com/clusterio/factorioClusterio/blob/34a0ce4dc32a9991314ae08daa0044c5151a45ad/plugins/subspace_storage/instance.js (look for sendRcon and this.instance.server.on("ipc-...")).  Also be sure to be looking at the clusterio-2.0 branch of factorioClusterioMod if you're inspecting the code there.

There's documentation detailing the process of making your own plugins in docs/, be sure to look at that.

**Comment by YagaoDirac** [comment]
Thanks, very helpful. I eventually saw the rcon tcp port. Only one extra question, I didn't find any detail about /sc. Is it the same as /c with the only difference that s is short for server? So, if I call anything registered with remote.add_interface, the event.player is always nil? I saw in the lua code, some of the functions start with, if event.player then return end.

**Comment by Hornwitser** [comment]
/sc is short for /silent-command.  It is the same as /command except it doesn't print the command being run to the in-game chat for everyone to see.
