### ISSUE TITLE
error running command npx clusterioctl slave generate-token --id 12345

### ISSUE THREAD

**Issue by n0t49a1n** [clusterio/factorioClusterio#387]
`PS C:\clusterio\factorio> npx clusterioctl slave generate-token --id 12345

+==========================================================+
I WARNING:  This is the development branch for the 2.0     I
I           version of clusterio.  Expect things to break. I
+==========================================================+

[fatal]
+----------------------------------------------------------------+
| Unexpected error occured while starting control, please report |
| it to https://github.com/clusterio/factorioClusterio/issues    |
+----------------------------------------------------------------+
SyntaxError: Unexpected token h in JSON at position 113
    at JSON.parse (<anonymous>)
    at startControl (C:\clusterio\node_modules\@clusterio\ctl\ctl.js:901:33)
PS C:\clusterio\factorio> npx clusterioctl slave generate-token --id 12345`

**Comment by Hornwitser** [comment]
Your control-config.json file is not valid JSON syntax. Please make sure it is valid JSON.
