### ISSUE TITLE
Allow basic server management from master web interface

### ISSUE THREAD

**Issue by Danielv123** [clusterio/factorioClusterio#47]
Authentication could be done using the RCON password which master stores and never distributes.

Could allow things like pausing, chat, save management, adding mods (by URL?)

**Comment by Danielv123** [comment]
Using http://www.erikosterberg.com/terminaljs/ and websockets, should allow to login to a slave and get factorio output and send console input.

**Comment by psihius** [comment]
@Danielv123 I'm closing this since it is old and we different ideas for the functionality for the Clusterio 2.0.
