### ISSUE TITLE
Master administration interface and remote node control

### ISSUE THREAD

**Issue by admalledd** [clusterio/factorioClusterio#89]
The key idea is that contributed server nodes are pure "dumb" clients. From those the existing cluster code and more is managed/updated. Thus master can push a update to all components to all nodes.

A major fault of the 60k spm project was coordinating server/client updates between all the node administrators.

- [ ]  Updating factorio
- [ ]  Updating client.js
- [ ]  Updating/configuring plugins
- [ ]  Updating/configuring mods
- [x]  Create node
- [x]  Shutdown/archive node
- [ ]  Download existing node (from master? or direct other server?) and spin up, allowing migration of nodes between hosts.

Things needed for administrating the above:

- [x] User authentication
- [x] Modular permission system
- [x] User management (deleting accounts, changing permissions)
- [x] System for letting a user claim a server to become admin on it

**Comment by psihius** [comment]
Assigning this to 2.0 project.
Since this has been posted there have been developments and changes, while the feature might not end up in the way it is described here, on the overall we will end up with something alike.

**Comment by Danielv123** [comment]
2.0 has a web interface located at https://github.com/clusterio/clusterioWeb , the latest version of it is hosted on https://clusterio.danielv.no/

It supports most of the required features from clusterctl and uses the clusterctl token to connect. The browser communicates directly with the master, just like clusterctl.
