### ISSUE TITLE
Get/Put limits/throttling

### ISSUE THREAD

**Issue by admalledd** [clusterio/factorioClusterio#98]
Recent question on discord raised the thought of public nodes.

A recommendation for that would be limiting Get/Put/Signals that can be sent to these nodes such that overall cluster health is not degraded.

Concepts:

* Max Get/Puts of <item> per <timespan>
* Balanced In/Out (eg, node requests 50,000 belt, needs to feed back other items to "offset" the cost)

Basically, take the idea of normal HTTP API limits, but apply them to clusterio's items as well. If a node is "nice", "trust" it more allowing more get/put etc.

**Comment by Heacien** [comment]
This sounds really interesting - it then could be used as a member/premium feature too

**Comment by Danielv123** [comment]
This feature would be part of https://github.com/clusterio/factorioClusterioMod
